### ISSUE TITLE
I can't install Ctrlr 5.4.2 under Windows 10 ....

### ISSUE THREAD

**Issue by TempyNick** [RomanKubiak/ctrlr#22] opened 2016-06-13 08:28 UTC
When i try to install Ctrlr 5.4.2 in Windows 10 i become the following message:

Error opening file for writing:
C:\Program Files (x86)\Ctrlr\Ctrlr-Win64.exe
Click Abort to stop the installation,
Retry to try again, or
Ignore to skip this file.

My system works with Windows 10 - 64bit. It makes no difference if i choose to install Ctrlr-Win32.exe.
Thank you for the answer how to fix this.

**Comment by RomanKubiak** [comment] 2016-06-17 13:52
THis is not a bug in any way. You need ADMIN privileges to write to those directories and i bet you are not running the installer as an Administrator user. So although i didn't want to change this i will change the installer, and this will be fixed in the next build for windows. For now just right click on the installer and choose "Run as administrator"

**Closed by RomanKubiak** 2016-06-17 13:52 UTC

**Comment by TempyNick** [comment] 2016-06-17 14:20
Thank you Roman!
Yes, it works. The only problem i have now is that the 32 bit Plug-in not is loaded by Cubase. I have Cubase 8 - 32 bit installed under Windows 10 - 64 bit. I did place the "Ctrlr-VST-Win32.dll" into the Cubase-directory: "VSTPlugins". When i start Cubase, i don't see the plug-in. Any idea?
Thanks again for your nice work!
Nick.
